### ISSUE TITLE
Failure on Spigot 1.20.2

### ISSUE THREAD

**Issue by SlimeDog** [PimvanderLoos/BigDoors#19]
Java 21
Spigot 1.20.2-3788
BigDoors 0.1.8.48-b1148

On server start-up, constant spam of these errors
```
[11:00:08] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[11:00:08] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:72)
[11:00:08] [Server thread/WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[11:00:08] [Server thread/WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.compatibility.FakePlayerInstantiator.getFakePlayer(FakePlayerInstantiator.java:129)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.compatibility.FakePlayerCreator.getFakePlayer(FakePlayerCreator.java:28)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.compatibility.ProtectionCompatManager.getPlayer(ProtectionCompatManager.java:110)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.compatibility.ProtectionCompatManager.checkForPlayer(ProtectionCompatManager.java:220)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.compatibility.ProtectionCompatManager.canBreakBlocksBetweenLocs(ProtectionCompatManager.java:268)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.BigDoors.canBreakBlocksBetweenLocs(BigDoors.java:487)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.moveBlocks.Opener.hasAccessToLocations(Opener.java:406)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.moveBlocks.PortcullisOpener.openDoorFuture(PortcullisOpener.java:166)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.moveBlocks.Opener.openDoorFuture(Opener.java:146)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.moveBlocks.Opener.openDoorFuture(Opener.java:115)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.moveBlocks.Opener.openDoorFuture(Opener.java:105)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.handlers.CommandHandler.openDoorCommand(CommandHandler.java:95)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.handlers.CommandHandler.onCommand(CommandHandler.java:837)
[11:00:08] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:00:08] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[11:00:08] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:879)
[11:00:08] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchServerCommand(CraftServer.java:864)
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:412)
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388)
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1179)
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:996)
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
[11:00:08] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[11:00:08] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ClientInformation.g()" because "clientinformation" is null
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1811)
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.level.EntityPlayer.<init>(EntityPlayer.java:323)
[11:00:08] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[11:00:08] [Server thread/WARN]:        ... 25 more
[11:00:08] [Server thread/INFO]: [BigDoors] You do not have permission to move the door to the new location!
[11:00:08] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[11:00:08] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:72)
[11:00:08] [Server thread/WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[11:00:08] [Server thread/WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.compatibility.FakePlayerInstantiator.getFakePlayer(FakePlayerInstantiator.java:129)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.compatibility.FakePlayerCreator.getFakePlayer(FakePlayerCreator.java:28)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.compatibility.ProtectionCompatManager.getPlayer(ProtectionCompatManager.java:110)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.compatibility.ProtectionCompatManager.checkForPlayer(ProtectionCompatManager.java:220)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.compatibility.ProtectionCompatManager.canBreakBlocksBetweenLocs(ProtectionCompatManager.java:268)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.BigDoors.canBreakBlocksBetweenLocs(BigDoors.java:487)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.moveBlocks.Opener.hasAccessToLocations(Opener.java:402)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.moveBlocks.PortcullisOpener.openDoorFuture(PortcullisOpener.java:166)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.moveBlocks.Opener.openDoorFuture(Opener.java:146)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.moveBlocks.Opener.openDoorFuture(Opener.java:115)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.moveBlocks.Opener.openDoorFuture(Opener.java:105)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.handlers.CommandHandler.openDoorCommand(CommandHandler.java:95)
[11:00:08] [Server thread/WARN]:        at nl.pim16aap2.bigDoors.handlers.CommandHandler.onCommand(CommandHandler.java:837)
[11:00:08] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:00:08] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[11:00:08] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:879)
[11:00:08] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchServerCommand(CraftServer.java:864)
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:412)
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388)
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1179)
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:996)
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
[11:00:08] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[11:00:08] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ClientInformation.g()" because "clientinformation" is null
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1811)
[11:00:08] [Server thread/WARN]:        at net.minecraft.server.level.EntityPlayer.<init>(EntityPlayer.java:323)
[11:00:08] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[11:00:08] [Server thread/WARN]:        ... 25 more
```

**Comment by PimvanderLoos** [comment]
Thanks for the report!

It looks like I forgot to finish the update for the FakePlayerCreator... Whoops. I'll work on a fix soon.

**Comment by SlimeDog** [comment]
Nice. Please release something. 😎

**Comment by PimvanderLoos** [comment]
The fix is available in the latest dev-build for the time being. A full release will follow soonish.

**Comment by SlimeDog** [comment]
All I see is:

Alpha 0.1.8.48
- b1148 (2023-09-22 19:19:46)

is three days old. I think that's the build I originally reported.

**Comment by PimvanderLoos** [comment]
The latest dev-build is [1150](https://pim16aap2.nl/BigDoors/). You may have to hard refresh the page to see the latest builds.

**Comment by SlimeDog** [comment]
Thanks. Please improve the caching on your web server.

**Comment by PimvanderLoos** [comment]
Oh, yeah, I know, the whole website is awful. I'd just rather spend my time working on AnimatedArchitecture than improving the page for the BigDoors dev builds. At least AA uses GH actions so I don't have to worry about all that stuff.
